### ISSUE TITLE
[Request] Videofeed and News API

### ISSUE THREAD

**Issue by ksh-b** [teamworktf/website_api#1]
Please add api's for the following page:
https://teamwork.tf/creators/videofeed

and add pagination and sources option for the news api

**Comment by teamworktf** [comment]
We will take this into consideration when we update the API.

**Comment by teamworktf** [comment]
The youtube policy prevents us from sharing this data, cannot create this endpoint.

**Comment by teamworktf** [comment]
Pagination and filtering on provider name is now possible in the NEWS api though.
