### ISSUE TITLE
Map creator endpoint doesnt seem to work

### ISSUE THREAD

**Issue by ksh-b** [teamworktf/website_api#5]
https://teamwork.tf/api/v1/map-creator/steamid/{steamid}?key=YOUR_API_KEY

Tried it with steam ids:
76561198008861029
76561198000713080

**Comment by teamworktf** [comment]
Hi, the documentation was wrong. The URL should be https://teamwork.tf/api/v1/gamemap-creator/steamid/{steamid}?key=YOUR_API_KEY

Fixed the documentation.
